# ********RoostGPT********

# Test generated by RoostGPT for test karate-nobel-prize-api-spec-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /accounts_post for http method type POST 
# RoostTestHash=53e96f9805
# 
# 

# ********RoostGPT********
Feature: API Testing to Create new Account
    
Background:

    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
  
Scenario: Successful creation of new account with specific commit hash

    Given path '/accounts'
    And request {"email": "user@example.com"}
    And header commit-hash = '1234567'
    When method post
    Then status 201
    And match responseHeaders contains {"api-version": "1.0.0", "commit-hash" : "928d28d"}

Scenario Outline: Creating accounts with invalid email addresses to observe errors

    Given path '/accounts'
    And request {"email": "<emailaddress>"}
    When method post
    Then status 400
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response contains {"error":"validation/email-pattern","description":"Descriptive Error Message"}

    Examples: 
    | emailaddress        |
    | user@examplecom     |
    | userexample.com     |
    | .user@example.com   |
    | user.@example.com   |
