# ********RoostGPT********

# Test generated by RoostGPT for test credential-wallet-karate-integration using AI Type Open AI and AI Model gpt-3.5-turbo-1106
# 
# ROOST_METHOD_HASH=87771cdd6d
# ROOST_METHOD_SIG_HASH=0a68a12aee
# 
#  ########## Scenario ########## 
# 
# {
#   background: 'Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: 'Delete authorization\r\n' +
#     '    Given authorization ID\r\n' +
#     '    When the client sends a DELETE request to "/authorizations/ID"\r\n' +
#     '    Then the response status code should be 200 for a successful delete\r\n' +
#     '    And the authorizations should not appear in GET request for "/authorizations"',
#   title: 'Delete authorization'
# }
# 

# ********RoostGPT********
Feature: Testing Authorization API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase

  Scenario: Delete authorization
    # Given the base URL is "http://localhost:8080"
    Given path '/authorizations/{id}'
    And request { id: 'someId' }
    When method delete
    # Then the response status code should be 200 for a successful delete
    Then status 200
    # And the authorizations should not appear in GET request for "/authorizations"
    # Add assertion to check if the authorization ID is deleted successfully
